apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-purchase-worker
  labels:
    app: fcg-purchase-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-purchase-worker
  template:
    metadata:
      labels:
        app: fcg-purchase-worker
    spec:
      containers:
      - name: fcg-purchase-worker
        image: 363256880455.dkr.ecr.sa-east-1.amazonaws.com/fcg-purchase-worker
        envFrom:
        - configMapRef:
            name: fcg-purchase-service-config
        - secretRef:
            name: fcg-purchase-service-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
